### ISSUE TITLE
New version of the old scene: DAIL - CSES scrubber

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1714]
I am replacing the myriad CSES "enhancements" with a brand new script called the "CSES scrubber". This should be cleaner (as it'll be one big pull, and I don't want that pull to resolve [at least] 5 issues).

The new CSES scrubber should have:

- [x] Handling to tell you're in training, working on a TIKL (if run on a TIKL, it'll ask for confirmation before proceeding)
- [x] An always-visible Excel sheet (end users want to see intricate details of the calculation)
- [x] A new class for MessageDetails that can be entered into an array for resorting
- [x] A developer mode override using Konami Code
- [x] Opens up an Excel doc for storage (no longer hidden)
- [x] Creates headers for the info about to go in Excel
- [x] Reads each message, enters contents (including calculations) in Excel
- [ ] Handling for reading Type 40 and 37 differently than the others
- [x] Handling for correctly rounding off partial pennies and adding them to the first MEMB
- [x] Determines open programs on CASE/CURR
- [x] No handling of HC, period... just skip it for now and include a message saying HC is now manual if HC is found (we can come back to it later if needed) (resolves #568)
- [x] Goes to MEMB and associates each PMI with a MEMB number, and adds to Excel
- [x] Removes underscores from PMIs so Ramsey can use it
- [x] Associate panels with each message, and add that to the Excel sheet
- [x] Separate sheets for the budget details
- [x] For MFIP: displaying budgets per each MEMB and UNEA type, which allows the end user to confirm whether-or-not they want to update
- [x] For MFIP: if UNEA panels are missing, script will exit and provide info to user
- [ ] For MFIP: if user indicates the budget-to-be is accurate, the script will update 
- [ ] If case is MFIP, SNAP is skipped
- [ ] For SNAP, a manual evaluation of "within the realm", with the +-10% being merely a "suggestion". Workers decide to skip or continue
- [ ] Also for SNAP: a warning if the case is using anticipated income in the PIC (resolves #375)
- [ ] Also also for SNAP: a warning if you're only representing one month on the PIC (resolves #294)
- [ ] An "other notes" section in a vastly improved CASE/NOTE dialog (lets you edit before it writes a case note) (resolves #1532)
- [ ] The income arranged in a grid/matrix in the CASE/NOTE (resolves #1395)
- [ ] Statistics handling at the end
- [ ] Remove any temp messageboxes, commented out dialogs, etc
- [ ] Test thoroughly
- [ ] Release script

Attached is a basic concept of my proposed workflow. I'll be working on this today (and resolving all other outstanding issues related to it, as we now have one issue to rule them all).

[CSES new proposal.pdf](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/99614/CSES.new.proposal.pdf)

**Comment by theVKC** [comment]
OK folks, I have some big new priorities I need to prepare for. I'm moving this back to next month. I feel bad, but I can't devote the time this month to working on it (and I should have dedicated script time in March).

**Comment by theVKC** [comment]
I wasn't able to test this well enough, so I'm moving it to the April release. @courtrightd: if you're holding messages, don't. But, I may want more messages next month if you're willing to oblige.

**Comment by theVKC** [comment]
Just proactively going to move this to the May release, because there's no way I can work on it in the next two weeks.

**Comment by theVKC** [comment]
I got a pretty good start on this, but could use some help getting it to update. Time is an issue for me at the moment. Anyone interested?

**Comment by theVKC** [comment]
@C-Love has agreed to take this on! Woot!

**Comment by theVKC** [comment]
I added this to the July release because it's coming into discussion here at DHS now, so it's becoming a bigger priority than it once was. @C-Love, let me know if you want to schedule some time to work through it next month.

**Comment by theVKC** [comment]
See https://github.com/MN-Script-Team/BZS-FuncLib/pull/259. I added logic to pass through error messages.

**Comment by C-Love** [comment]
This is ready for all kinds of testing. I will pull it in shortly. 

This is what we ended up with based on our recent conversation:
1. Gathers DAIL messages and creates a spreadsheet to display and work with them
2. Identify which UNEA panel each message is associated with
3. Determines if SNAP or MFIP case and if  HRF or REVW is due
4. If SNAP active the case will look at SNAP ELIG to gather budget information
5. If SNAP active, UNEA detail will be added to a new worksheet on Excel document
6. Dialog will appear based on programs active. Workers will be able to add notes, sign case note, indicate if Excel sheet should remain open at end of script, and indicate if additional review is needed. IF SNAP is active and there is either a change in the amount of CS OR the income appears to exceed 130% FPG, the script will default to having the panels reviewed by worker.
7. If SNAP case needs income reviewed, a dialog for each UNEA panel will ask worker if income needs adjusting (Yes/No only).
8. IF MFIP, script will add worksheet to Excel document and then attempt to update UNEA upon worker confirmation.
9. Case note! and close spreadsheet

Developer Mode exists.

I would bet @theVKC had way more amazing elements in mind here - but I think this will be a good start and it is all modernized for any enhancements.
