### ISSUE TITLE
Add "list of scripts" vbs file and update main menus to use it

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#2159]
This is related to workflow scripts. I've got this.

Update: here are the steps I'm taking:

- [x] Script class: add URL property which is self-generating
- [x] Script class: add instructions URL property which is self-generating
- [x] Script class: add category property
- [x] Script class: add subcategory property
- [x] Script class: add workflows property
- [x] Script class: add category property
- [x] Script class: remove button-size property (I'm going to be aligning all button sizes)
- [x] Script class: remove file-name property (this is now self-generating as part of the URL property)
- [x] Rename script class to script_bowie for testing purposes
- [x] Subcategory buttons automatically create themselves and link to each other correctly
- [x] Add reference to this file on ACTIONS - MAIN MENU (with temp URL for testing)
- [x] Add list of all ACTIONS scripts to this file
- [x] Add list of all BULK scripts to this file
- [x] Add list of all DAIL scripts to this file
- [x] Add list of all NAV scripts to this file
- [x] Add list of all NOTES scripts to this file
- [x] Add list of all NOTICES scripts to this file
- [x] Add list of all UTILITIES scripts to this file
- [x] Add release dates to all scripts (approximate for older scripts)
- [x] Test with actions scripts (by pulling ACTIONS - MAIN MENU to master)
- [x] Correct temporary redirect URL from branch to master on ACTIONS - MAIN MENU
- [ ] Remove description from dialog display, rearrange itens into grid
- [ ] Add description MsgBox to dialog display (see #2411)
- [ ] Add function to display new scripts, scripts from last 3 months
- [ ] Replace script class in FuncLib with the new one, but before pulling this in, pull in other changes after-hours (https://github.com/MN-Script-Team/BZS-FuncLib/issues/163)
- [ ] Rename `script_bowie` objects to `script` before going live (after `script` class is updated in FuncLib) (https://github.com/MN-Script-Team/BZS-FuncLib/issues/163)
- [ ] Add `declare_main_menu_dialog` to FuncLib (https://github.com/MN-Script-Team/BZS-FuncLib/issues/163)
- [ ] Replace BULK main menu with a dynamically created one
- [ ] Replace OTHER NAV main menu with a dynamically created one
- [ ] Replace NOTES main menu with a dynamically created one
- [ ] Replace NOTICES main menu with a dynamically created one
- [x] Replace UTILITIES main menu with a dynamically created one
- [ ] Remove `declare_main_menu_dialog` from ACTIONS - MAIN MENU
- [ ] Remove `declare_main_menu_dialog` from UTILITIES - MAIN MENU
- [ ] Create and disburse instructions for how to update this file

**Comment by theVKC** [comment]
This is now tied to the June release as Bowie was moved to June.

**Comment by theVKC** [comment]
Update: this is successfully creating an array of scripts-as-script-objects, which can be iterated through and modified when needed.

I just need to add all of the content at this point. Then it should be ready for deployment, and the issue should be closed. I have other work going on this week but I am hoping to squeak it by (since it's primarily just a list of scripts).

**Comment by theVKC** [comment]
So I finished this, but it's breaking when trying to open large scripts. I've noticed issues loading the BULK DAIL list, and I noticed issues with CAF when I had more than 5 subcategories.

Right now, I'm using classes and objects iterated through an array. I'm thinking ButtonPressed doesn't seem to like this arrangement and it wants a plain-jane array.

Tomorrow's a busy day but I will try to get it done. Worst case, this is delayed a month while I work out the kinks. I'd prefer not to, though, this will be a very helpful new feature.

**Comment by theVKC** [comment]
I wasn't able to get this whole thing done this month. But, the list itself is going live for the June release, so that's a really good thing. And it was the original scope of this issue, so I can sleep tonight knowing that. :)

**Comment by theVKC** [comment]
We ran into a bug with this... apparently there is a 453 control limit on things you can have in dialogs across a script in its entirety. Upon hitting a dialog with the 453rd control, BlueZone throws an Exception Access Violation and closes. My SIR instructions buttons were hitting this.

I resolved the issue by renaming each dialog as `dialog1` and assigning a numeric value to it, then defining the dialog immediately proceeding the `dialog` call (which I have removed the variable containing the dialog from this call). This seems to work fine, and was part of the plan for #1999 and #2000 anyway.

So, work continues, hopefully this month. I will start by pulling the bulk main-menu in at some point in the coming days and we can use this as a good test.

**Comment by theVKC** [comment]
This is appearing to require an update to _every single script_ in order to work. All scripts will need dialogs declared with the new parameters (`dialog1` as name, and positioned just above the `Dialog` command, which will display the last defined dialog).

The list of scripts is complete, but mass changes will be needed. I am debating closing this issue and starting a few new ones, and going at this month-to-month until the work is complete. I am open to suggestions on that from @MN-Script-Team/county-agency-scriptwriters.

**Comment by CDPotter** [comment]
Will reopen once workflows are cracked.
