### ISSUE TITLE
project mic drop

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#710]
A plan to build a comprehensive eligibility review interview scheduler for SNAP and MFIP.

Task list:
- [x] Asks for dates on dialog (save the first 8 days of the month)
- [x] Goes into each case on REVS and logs the ones with a review requiring an interview
- [x] Adds day/time of interview based on earlier dialog
- [x] Shows an Excel list of all of the cases
- [x] Case notes each case
- [x] Sends Appointment letter for each case
- [x] Includes developer mode (#713)
- [x] Includes link to instructions page (#1700)
- [x] Includes multi-user functionality (can run on multiple caseloads) (#1084) - Assigned: @theVKC
- [x] The user can cap the reviews scheduled per worker (#1083) - Assigned: @theVKC
- [x] A `create_dynamic_calendar_dialog` function which can output selected dates as an array (will be moved to FuncLib when completed) (#1711) - Assigned: @theVKC
- [x] A 'create_outlook_appointment` function which can optionally update your Outlook calendar with all scheduled dates. - Assigned: @theVKC
- [x] Statistics gathering handling - Assigned: @IlseFerris
- [x] A separate DAIL scrubber script to process the missed interviews (#711)
- [x] Remove Veronica's elitist functionality - Assigned: @CDPotter
- [x] Standardize date format for the TIKL (MM/DD/YYYY) - Assigned: @theVKC
- [x] Add to bulk MAIN MENU before pulling into master - Assigned: @IlseFerris
- [x] Research why on-the-hour appointment scheduling in Outlook does not schedule out for the time period selected (e.g.: 30 minute appt only scheduled from 800-800) 
- [x] Date on notice that paperwork needs to be submitted to the agency by has an excess "/" mark

**Comment by theVKC** [comment]
@IlseFerris, I'm taking you off of this as the assignee. This is clearly being worked on by a team, and I don't need it mucking up your task list. :)

**Comment by theVKC** [comment]
Task list update allows me to close #1083, #1084, and #1711.

**Comment by theVKC** [comment]
FYI all: I'm targeting this for the March release. I will be formally closing the Mic Drop milestone today.

**Comment by theVKC** [comment]
@IlseFerris: see #1889 about a planned upgrade to the BULK Main Menu... Perhaps that step should come before adding this script?

**Comment by theVKC** [comment]
Now that this is close to finished, we need to formalize a multi agency test plan. I believe the following have shown interest in the past:

* @courtrightd 
* @GayS / @MelissaFox-Stearns / @StormageddonDLOA 
* @C-Love / @Y-Lor-Y / @kaleykobber 
* @LaLarson 

@IlseFerris: I think we should find a few teams at Hennepin to pilot this for the upcoming month.

**Comment by theVKC** [comment]
Made the decision to move this to the April release to allow Anoka, Ramsey, and Hennepin a month of testing pre-master release.

**Comment by theVKC** [comment]
@IlseFerris: did we fix the date issue?

**Comment by IlseFerris** [comment]
I thought @CDPotter submitted a fix on the date, but I could be mistaken.

**Comment by CDPotter** [comment]
Things I've fixed since 2/18/16:

-changed logic to prevent issues where MS and ACTV renewals were being assessed as MF and ACTV thus not deleting them if there was a SNAP CSR or renewal in 12 more months.

- max_reviews_per_worker is getting ABS'd which causes type mismatch error: Made conditional based on if it's entered

- the text for the maximum interviews is getting cut off: Fixed

Which date issue are we talking about?

**Comment by theVKC** [comment]
"Research why on-the-hour appointment scheduling in Outlook does not schedule out for the time period selected (e.g.: 30 minute appt only scheduled from 800-800)"...

I have done a bit of research on this. It appears to be only happening with the very first appointment, and I think it has something to do with an array and determining the actual length of the first appointment. As this is my function, I will take the lead in investigating.

**Comment by theVKC** [comment]
Say @IlseFerris, I'm starting to think it might be easier to simply remove the Outlook functionality for now, and add it as an enhancement request sometime down the road. This is buggy and I worry it won't work right on other versions of Outlook. Calendar seems to behave differently on 2016 vs 2013.

**Comment by IlseFerris** [comment]
Agreed. I will update the script to remove the function. This script should be good to go for the June release then (woot woot!)

**Comment by theVKC** [comment]
Yay yay yay yay yay!!!
